name = "LearnLean"
version = "0.1.0"
defaultTargets = ["IntroToLean", "LambdaCalculus", "errata"]
builtinLint = true

[[lean_lib]]
name = "IntroToLean"
globs = ["IntroToLean.+"]

[[lean_lib]]
name = "LambdaCalculus"
globs = ["LambdaCalculus.+"]

[[lean_exe]]
name = "errata"
root = "Main"
